---
title: "Development actions history"
output: html_document
editor_options: 
  chunk_output_type: console
---

All commands that you use to use when developing packages...

# First time just after creating the project

- Fill the following chunk to create the DESCRIPTION of your package

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "A package to draw tour maps given a route",
    Description = "The package provides broad functionality to draw tour maps with the suppot of OSM data and a georeferencer.",
    `Authors@R` = c(
      person("Yokana", "Katumba", email = "wagnerjoha.leipzig@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0000-0000-0000"))
    )
  )
)
# Define License with use_*_license()
usethis::use_gpl3_license("Yokana Katumba")
usethis::use_pipe()
```

# Inflate save_data.Rmd

Start by inflating `dev/flat_save_data.Rmd`:

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_bicycle_pkg.Rmd",
               vignette_name = "dev-flat_bicycle_pkg",
               overwrite = T)

```
