---
title: "Touring Maps"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tidyverse)
library(sf)
library(tidygeocoder)
library(osrm)
library(maptiles)
library(ggrepel)
library(glue)
library(rlang)
library(scales)
library(patchwork)
library(tidyterra)
library(ggspatial)
library(httr)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## Loading the data

```{r function-load_spatial_data}
#' load_spatial_data Get the spatial data
#' At this point the package expects a shapefile for administrative boundaries. This data can be found
#' with local or national authorities or on specialized websites like https://www.diva-gis.org/.
#'
#' The Shapefile has to be stored under `data/`in the project directory and needs to contain a column with
#' a geometry, the administrative level of interest (for example districts) and a unique identifier for the 
#' administrative units of interest.
#'
#' Additionally the CRS of the final map needs to be specified. The default value is WGS84.
#'
#' @return 1
#' @export
#'
#' @examples

load_spatial_data <- function(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832) {

  dir <- getwd()
  dir <- glue("{dir}/data/{name}.shp")

  column <- ensym(column)

  municipalities <- st_read(dir)

  municipalities_tb <- as_tibble(municipalities) %>%
    select(!!column, geometry)

  if (!is.null(filter_by)) {
    municipalities_tb <- municipalities_tb %>%
      filter(!!column %in% filter_by)
  }

  municipalities_sf <- st_as_sf(municipalities_tb)
  municipalities_sf <- st_transform(municipalities_sf, crs = crs)

  return(municipalities_sf)
}
```


```{r examples-load_spatial_data()}
#' Load the german municipalities from https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-250-000-stand-01-01-vg250-01-01.html
data <- load_spatial_data(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832)

head(data)
```

```{r tests-load_spatial_data()}
# We want to check if the retrieved dataset has the desired structure
test_types <- function() {
  data <- load_spatial_data(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832)
  expect_is(data, "sf") 
  expect_true("geometry" %in% names(data))
}

test_that("load_spatial_dat works", {
  test_types()
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_bicycle_pkg.Rmd", vignette_name = "Minimal")
```
