# WARNING - Generated by {fusen} from dev/flat_bicycle_pkg.Rmd: do not edit by hand

# We want to check if the retrieved dataset has the desired structure
test_types <- function() {
  data <- load_spatial_data(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832)
  expect_is(data, "sf") 
  expect_true("geometry" %in% names(data))
}

test_that("load_spatial_dat works", {
  test_types()
})
