# WARNING - Generated by {fusen} from dev/flat_bicycle_pkg.Rmd: do not edit by hand

#' load_spatial_data Get the spatial data
#'
#' @importFrom tidygeocoder geocode
#' @importFrom sf st_as_sf st_crs st_transform
#' @importFrom dplyr filter
#' @importFrom tibble tibble
#' @return A data frame of class sf
#' @export
#'
#' @examples


#' data_geocode <- geocode_locations(locations = c("Leipzig", "Lützen", "Weißenfels", "Naumburg", "Bad Kösen", "bad Sulza", "Auerstedt"), crs = 25832)
#'
#' head(data_geocode)
geocode_locations <- function(locations = c("Leipzig", "Lützen", "Weißenfels", "Naumburg", "Bad Kösen", "bad Sulza", "Auerstedt"), crs = 25832) {

  part_vector <- seq(1, length(locations))

  stops_to_geocode <- tibble(
    part = part_vector,
    location = locations,
  )

  stops_geocoded <- stops_to_geocode %>%
    geocode(location, method = "osm") %>%
    filter(!is.na(long) & !is.na(lat)) %>%
    st_as_sf(coords = c("long", "lat"), crs = st_crs("EPSG:4326"))

  locations_sf <- stops_geocoded

  crs <- st_crs(25832)
  locations_sf["geometry"] <- lapply(locations_sf["geometry"], st_transform, crs) 

  return(locations_sf)
}


#' load_spatial_data Get the spatial data
#'
#' @importFrom glue glue
#' @importFrom rlang ensym
#' @importFrom sf st_read st_as_sf st_transform
#' @importFrom dplyr select filter
#' @importFrom tibble as_tibble
#' @return A data frame
#' @export
#'
#' @examples

#' data <- load_spatial_data(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832)
#'
#' head(data)
load_spatial_data <- function(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832) {

  dir <- system.file("data", package = "YourPackageName")
  dir <- glue::glue("{dir}/{name}.geojson")

  column <- ensym(column)

  municipalities <- st_read(dir)

  municipalities_tb <- as_tibble(municipalities) %>%
    select(!!column, geometry)

  if (!is.null(filter_by)) {
    municipalities_tb <- municipalities_tb %>%
      filter(!!column %in% filter_by)
  }

  municipalities_sf <- st_as_sf(municipalities_tb)
  municipalities_sf <- st_transform(municipalities_sf, crs = crs)

  # # save municipalities_sf as rds
  # write_rds(municipalities_sf, glue::glue("{dir}/data/{name}.rds"))


  return(municipalities_sf)
}
