# WARNING - Generated by {fusen} from dev/flat_bicycle_pkg.Rmd: do not edit by hand

#' load_spatial_data Get the spatial data
#'
#' @importFrom glue glue
#' @importFrom rlang ensym
#' @importFrom sf st_read st_as_sf st_transform
#' @importFrom dplyr select filter
#' @importFrom tibble as_tibble
#' @return A data frame
#' @export
#'
#' @examples

#' data <- load_spatial_data(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832)
#'
#' head(data)
load_spatial_data <- function(name = "VG250_KRS", column = "SN_L", filter_by = NULL, crs = 25832) {

  dir <- getwd()
  dir <- glue::glue("{dir}/data/{name}.shp")

  column <- ensym(column)

  municipalities <- st_read(dir)

  municipalities_tb <- as_tibble(municipalities) %>%
    select(!!column, geometry)

  if (!is.null(filter_by)) {
    municipalities_tb <- municipalities_tb %>%
      filter(!!column %in% filter_by)
  }

  municipalities_sf <- st_as_sf(municipalities_tb)
  municipalities_sf <- st_transform(municipalities_sf, crs = crs)

  # # save municipalities_sf as rds
  # write_rds(municipalities_sf, glue::glue("{dir}/data/{name}.rds"))


  return(municipalities_sf)
}
